development:
  adapter: mysql2
  database: sc_net_development
  username: root
  password:

test:
  adapter: mysql2
  database: sc_net_test
  username: root
  password:

production:
  adapter: mysql2
  database: sc_net_production
  username: root
  password:

